/*
 * Writes migrations/0003_seed_content.sql from the content that is currently
 * hardcoded in the page templates, so moving these pages into the database
 * loses nothing. Re-runnable: every insert is guarded by a NOT EXISTS check on
 * a natural key, so applying the file twice does not duplicate rows.
 *
 *   node --experimental-strip-types scripts/generate-seed.mjs
 */
import { writeFileSync } from 'node:fs';
import { DESTINATIONS } from '../src/data/destinations.ts';

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => q(JSON.stringify(v ?? []));

const out = [];
out.push(`-- Generated by scripts/generate-seed.mjs — do not edit by hand.`);
out.push(`-- Seeds the destination guides and the repeatable About/Scholarship rows`);
out.push(`-- from what the page templates used to hardcode.`);
out.push('');

/* ---- destinations ------------------------------------------------------ */

const GRADIENT = {
  uk: '#2e4a7a,#4d70a8',
  usa: '#963c3c,#c25a5a',
  canada: '#a02c2c,#d15b5b',
  malaysia: '#1e786e,#22a396',
  finland: '#2a5b8f,#5b8fc4',
  france: '#31407e,#5c6bb0',
  malta: '#8c2b3c,#bd5a6b',
  netherlands: '#b4591f,#dd8b4a',
  'new-zealand': '#1f4d5c,#3d7d92',
  spain: '#9a5a12,#c98a3c',
};

out.push('-- Destination guides');
DESTINATIONS.forEach((d, i) => {
  out.push(
    `INSERT INTO destinations (slug, country, short, flag, tagline, answer, intro, why, tuition, living, currency, intakes, work_rights, post_study, english_req, academic_req, visa_name, visa_steps, scholarships, universities, official_label, official_url, faqs, card_image, gradient, sort_order, active)
SELECT ${q(d.slug)}, ${q(d.country)}, ${q(d.short)}, ${q(d.flag)}, ${q(d.tagline)}, ${q(d.answer)}, ${q(d.intro)}, ${j(d.why)}, ${q(d.tuition)}, ${q(d.living)}, ${q(d.currency)}, ${q(d.intakes)}, ${q(d.workRights)}, ${q(d.postStudy)}, ${q(d.englishReq)}, ${q(d.academicReq)}, ${q(d.visaName)}, ${j(d.visaSteps)}, ${j(d.scholarships)}, ${j(d.universities)}, ${q(d.officialSource?.label)}, ${q(d.officialSource?.url)}, ${j(d.faqs)}, ${q(d.cardImage || null)}, ${q(GRADIENT[d.slug] || '#2e4a7a,#4d70a8')}, ${i * 10}, 1
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = ${q(d.slug)});`
  );
});
out.push('');

/* ---- repeatable page items --------------------------------------------- */

const items = [];
const add = (group, row) => items.push({ group, ...row });

// About — Key Skills and Core Competences
[
  ['Adaptability & Flexibility', 'arrow-down-box'],
  ['Effective Problem-Solving', 'shield-x'],
  ['Strong Communication Skills', 'chat'],
  ['Analytical Thinking & Decision Making', 'grid-lines'],
  ['Leadership & Teamwork', 'users'],
  ['Project Management Skills', 'kanban'],
  ['Technical Proficiency', 'cog'],
  ['Time Management & Prioritisation', 'clock'],
  ['Creativity & Innovation', 'bulb'],
  ['Global Perspective', 'globe'],
].forEach(([title, icon], i) => add('about.skills', { title, icon, sort_order: i * 10 }));

// About — Six Reasons to Choose Us
[
  "We're with you every step of the way",
  'Student satisfaction is our top priority',
  'A clear, efficient application process',
  'Specialising across 10 countries, not just one',
  'Complimentary end-to-end counselling',
  'Zero consultancy fees for students, guaranteed',
].forEach((title, i) =>
  add('about.reasons', { title, sort_order: i * 10, accent: i === 5 ? 'bridge' : '' })
);

// About — Our Company History
[
  ['2019', 'Established', 'Cloud Bridge (CBC) was founded in Dhaka to make studying abroad accessible and transparent for Bangladeshi students.'],
  ['2020', 'Virtual Counselling Launched', 'Introduced fully remote counselling and application support so students never had to pause their plans.'],
  ['2021', 'Multi-Country Expansion', 'Added partner universities in Canada and mainland Europe alongside our original UK and USA network.'],
  ['2022', 'Sylhet Branch Opened', 'Opened our second office in Sylhet to bring in-person counselling closer to students in the northeast.'],
  ['2023', '5,000+ Students Milestone', 'Crossed 5,000 successful student placements across our partner destinations.'],
  ['2024', 'Malaysia & Oceania Added', 'Extended our network to Malaysia and New Zealand, rounding out a 10-country portfolio.'],
  ['2025', '500+ Partner Universities', 'Our partner network grew to 500+ universities and colleges across all 10 destinations.'],
  ['2026', 'Today', 'A redesigned digital platform and expanded scholarship support — with plenty more ahead.'],
].forEach(([subtitle, title, body], i) =>
  add('about.history', { subtitle, title, body, sort_order: i * 10 })
);

// Scholarship — Types of Funding
[
  ['Merit-Based Scholarships', 'Awarded for strong academic results — often applied automatically during admission.', 'Academic Results', 'cap'],
  ['Need-Based Funding', 'Partial or full tuition support based on demonstrated financial need.', 'Tuition Support', 'coin'],
  ['Country & University Grants', 'Destination-specific and university-specific awards for international students.', 'Destination-Specific', 'globe'],
  ['Talent & Sports Awards', 'Funding for demonstrated ability in sports, arts, leadership, or extracurriculars.', 'Non-Academic', 'trophy'],
  ['Application & Fee Waivers', 'Reduced or waived application fees and early-bird tuition discounts at partner institutions.', 'Cost Savings', 'card'],
].forEach(([title, body, subtitle, icon], i) =>
  add('scholarship.types', { title, body, subtitle, icon, sort_order: i * 10 })
);

// Scholarship — How Scholarship Support Works
[
  ['Step 1', 'Free Eligibility Check', 'Tell us your academics, destination, and budget — we screen every scholarship you could realistically qualify for.'],
  ['Step 2', 'Profile & Document Review', 'Your counsellor reviews transcripts, test scores, and statements to strengthen your scholarship case.'],
  ['Step 3', 'Application & Matching', 'We apply on your behalf to matching university and country-specific funding alongside your admission.'],
  ['Step 4', 'Award & Visa Support', 'Once your funding is confirmed, we carry straight on into visa document prep — no gaps, no guesswork.'],
].forEach(([subtitle, title, body], i) =>
  add('scholarship.steps', { subtitle, title, body, sort_order: i * 10 })
);

// Scholarship — Scholarships by Destination
[
  ['United Kingdom', 'Merit scholarships, Chevening-style awards, and university-specific bursaries for international students.', '/destinations/study-in-uk', 'Explore UK Options', 'bridge'],
  ['Malaysia', 'Tuition fee waivers and living-cost-friendly funding at partner universities across Malaysia.', '/destinations/study-in-malaysia', 'Explore Malaysia Options', 'harbor'],
  ['USA', 'Merit-based awards and assistantship routes at partner colleges and universities across the USA.', '/destinations/study-in-usa', 'Explore USA Options', 'sunrise'],
].forEach(([title, body, link_url, link_label, accent], i) =>
  add('scholarship.destinations', { title, body, link_url, link_label, accent, sort_order: i * 10 })
);

// Scholarship — FAQs
[
  ['Is the scholarship check really free?', 'Yes — reviewing your eligibility and matching you with available funding is part of our free consultation, with no upfront cost to you.'],
  ['Do all universities offer scholarships?', 'Most of our 500+ partner universities offer at least one form of funding, though the amount and type vary by course, intake, and your academic profile.'],
  ['When should I apply for a scholarship?', 'As early as possible. Many merit and country-specific awards close before general admission deadlines, so we check funding options the moment you shortlist a university.'],
  ['Can I combine a scholarship with a student loan?', 'In most cases, yes. A scholarship simply reduces the amount you need to fund separately — your counsellor can help you plan both together.'],
  ['Will a low IELTS score affect my scholarship chances?', "It can for some merit awards, but many need-based and country-specific grants weigh academic results and financial need more heavily. We'll tell you honestly where you stand."],
].forEach(([title, body], i) => add('scholarship.faqs', { title, body, sort_order: i * 10 }));

out.push('-- Repeatable page rows (About + Scholarship)');
for (const it of items) {
  out.push(
    `INSERT INTO page_items (group_key, title, subtitle, body, icon, link_url, link_label, accent, sort_order, active)
SELECT ${q(it.group)}, ${q(it.title ?? '')}, ${q(it.subtitle ?? '')}, ${q(it.body ?? '')}, ${q(it.icon ?? '')}, ${q(it.link_url ?? '')}, ${q(it.link_label ?? '')}, ${q(it.accent ?? '')}, ${it.sort_order}, 1
WHERE NOT EXISTS (SELECT 1 FROM page_items WHERE group_key = ${q(it.group)} AND title = ${q(it.title ?? '')});`
  );
}
out.push('');

writeFileSync(new URL('../migrations/0003_seed_content.sql', import.meta.url), out.join('\n'));
console.log(`Wrote migrations/0003_seed_content.sql — ${DESTINATIONS.length} destinations, ${items.length} page items`);
